#!/bin/bash

export RG_NAME=rg-aci-test
location=eastus
export ACI_NAME=aci-go-test
img_name="mcr.microsoft.com/oss/nginx/nginx:1.9.15-alpine"

az group create \
    --resource-group $RG_NAME \
    --location $location

az container create \
    --resource-group $RG_NAME \
    --name $ACI_NAME \
    --image $img_name \
    --dns-name "$ACI_NAME-url" \
    --ports 80
