#!/bin/bash

# This script deploys the following resources: 
# 	- 1 Azure VNET.
# 	- 2 Subnets (one for the VMs, and another for the Azure Bastion).
# 	- 1 NSG allowing HTTP traffic at the subnet level.
# 	- 1 Azure Bastion.
# 	- 1 Linux VMSS with private access.
# 	- 1 Public Load Balancer with the VMSS as the Backend Pool.
# 	- 1 Public IP.

RG_NAME="rg-vmss-test"
VNET_NAME="vnet-test"
SB_NAME="sb-test"
SB_BASTION="AzureBastionSubnet"
BASTION_NAME="bastion-test"
VMSS_NAME="vmss-test"
IP1_NAME="pubip-bastion"
IP2_NAME="pubip-lb"
NSG_NAME="nsg-test"
LB_NAME="pub-lb-test"
location="eastus2"
MY_PUB_IP="$(dig +short myip.opendns.com @resolver1.opendns.com)"
RL_NAME="AllowHttpTrafficFromClient"
LB_FE="public-frontend"
LB_BE="vmss-backend-pool"
LB_PROBE="http-probe"

az group create \
    --resource-group $RG_NAME \
    --location $location

az network vnet create \
    --resource-group $RG_NAME \
    --name $VNET_NAME \
    --address-prefixes 10.1.0.0/16

az network nsg create \
    --resource-group $RG_NAME \
    --name $NSG_NAME

az network nsg rule create \
    --resource-group $RG_NAME \
    --nsg-name $NSG_NAME \
    --name $RL_NAME \
    --priority 100 \
    --source-address-prefixes $MY_PUB_IP \
    --source-port-range "*" \
    --access Allow \
    --direction Inbound \
    --protocol Tcp \
    --destination-port-ranges 80 8080 \
    --destination-address-prefixes "*"

az network vnet subnet create \
    --resource-group $RG_NAME \
    --name $SB_BASTION \
    --vnet-name $VNET_NAME \
    --address-prefixes 10.1.1.0/24 \

az network vnet subnet create \
    --resource-group $RG_NAME \
    --name $SB_NAME \
    --vnet-name $VNET_NAME \
    --address-prefixes 10.1.69.0/24 \
    --network-security-group $NSG_NAME

IPs=($IP2_NAME $IP1_NAME)
for ip in "${IPs[@]}"; do 
    az network public-ip create \
	--resource-group $RG_NAME \
	--name $ip \
	--sku Standard \
	--allocation-method Static \
	--zone 1
done

az network lb create \
    --resource-group $RG_NAME \
    --name $LB_NAME \
    --public-ip-address $IP2_NAME \
    --sku Standard \
    --frontend-ip-name $LB_FE \
    --backend-pool-name $LB_BE

az network lb probe create \
    --resource-group $RG_NAME \
    --lb-name $LB_NAME \
    --name $LB_PROBE \
    --protocol tcp \
    --port 80

az network lb rule create \
    --resource-group $RG_NAME \
    --lb-name $LB_NAME \
    --name $RL_NAME \
    --protocol tcp \
    --frontend-port 80 \
    --backend-port 80 \
    --frontend-ip-name $LB_FE \
    --backend-pool-name $LB_BE \
    --probe-name $LB_PROBE \
    --disable-outbound-snat true \
    --idle-timeout 15

az network lb outbound-rule create \
    --address-pool $LB_BE \
    --frontend-ip-configs $LB_FE \
    --idle-timeout 5 \
    --lb-name $LB_NAME \
    --name allow-out-traffic \
    --outbound-ports 10000 \
    --protocol All \
    --resource-group $RG_NAME

az vmss create \
    --resource-group $RG_NAME \
    --name $VMSS_NAME \
    --image "Ubuntu2204" \
    --instance-count 2 \
    --orchestration-mode Uniform \
    --vm-sku "Standard_B1ls" \
    --admin-username "azureuser" \
    --authentication-type ssh \
    --generate-ssh-keys \
    --public-ip-address "" \
    --subnet $SB_NAME \
    --vnet-name $VNET_NAME \
    --storage-sku "Standard_LRS" \
    --load-balancer $LB_NAME \
    --backend-pool-name $LB_BE

az network bastion create  \
    --name $BASTION_NAME \
    --resource-group $RG_NAME \
    --public-ip-address $IP1_NAME \
    --vnet-name $VNET_NAME

export RG_NAME
export VNET_NAME
export SB_NAME
export BASTION_NAME
export VMSS_NAME
export IP1_NAME
export IP2_NAME
export NSG_NAME
export LB_NAME
export MY_PUB_IP
